config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  get 'pages/about'
  get 'pages/privacy'
  get 'pages/terms'
  get 'pages/successfulorder', to:"pages#successfulorder"
  get 'pages/index', to:"pages#index"
  get 'pages/submitorder', to:"pages#submitorder"
  get 'pages/email', to:"pages#email"
  #get "../notifications/index" => "NotificationController#index"
  

  devise_for :users,
    controllers: {
      # omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }

  resources :restaurants do
    resources :comments, module: :restaurants
    resources :menu_items
    resources :addresses, module: :restaurants
  end

  resources :comments do
    resources :comments, module: :comments
  end

  resources :categories

  resources :addresses

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/menu_item.rb
# == Schema Information
#
# Table name: menu_items
#
#  id                      :bigint           not null, primary key
#  ancestry                :string           not null
#  ancestry_depth          :integer          default(0)
#  cached_votes_down       :integer          default(0)
#  cached_votes_score      :integer          default(0)
#  cached_votes_total      :integer          default(0)
#  cached_votes_up         :integer          default(0)
#  cached_weighted_average :float            default(0.0)
#  cached_weighted_score   :integer          default(0)
#  cached_weighted_total   :integer          default(0)
#  children_count          :integer          default(0)
#  description             :text             not null
#  favoritable_score       :text
#  favoritable_total       :text
#  name                    :string(150)      not null
#  price_cents             :integer          default(0), not null
#  price_currency          :string           default("USD"), not null
#  slug                    :string           not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  category_id             :bigint           not null
#  restaurant_id           :bigint           not null
#
# Indexes
#
#  index_menu_items_on_ancestry       (ancestry)
#  index_menu_items_on_category_id    (category_id)
#  index_menu_items_on_restaurant_id  (restaurant_id)
#  index_menu_items_on_slug           (slug)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (restaurant_id => restaurants.id)
#
class MenuItem < ApplicationRecord
  # include MeiliSearch::Rails

  extend FriendlyId
  # extend Pagy::Meilisearch
  extend Pagy::Searchkick

  belongs_to :restaurant
  belongs_to :category

  has_one_attached :image

  has_ancestry counter_cache: true, cache_depth: true

  friendly_id :name, use: :scoped, scope: [:restaurant]

  monetize :price_cents

  acts_as_taggable_on :ingredients
  # acts_as_taggable_on :allergens

  acts_as_favoritor
  acts_as_favoritable

  acts_as_voter

  # meilisearch do
  #   attribute :name
  #   attribute :description
  #   attribute :category
  #   attribute :price_range

  #   filterable_attributes [:category]
  #   sortable_attributes [:created_at, :updated_at]
  # end

  searchkick searchable: [:name, :category],
             word_start: [:name, :description, :category], 
             word_middle: [:name, :description, :category], 
             word_end: [:name, :description, :category]

  def search_data
    {
      name: name,
      description: :description,
      category: category.display_name,
      price: price
      # popularity: popularity
    }
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[ show edit update destroy ]

  # GET /menu_items or /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1 or /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items or /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to menu_item_url(@menu_item), notice: "Menu item was successfully created." }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1 or /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to menu_item_url(@menu_item), notice: "Menu item was successfully updated." }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1 or /menu_items/1.json
  def destroy
    @menu_item.destroy

    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: "Menu item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_item_params
      params.require(:menu_item).permit(:restaurant_id, :category_id, :name, :description, :price, :image)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item, class: "contents") do |form| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :restaurant_id %>
    <%= form.text_field :restaurant_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.text_field :category_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/menu_items/_menu_item.html.erb
<div id="<%= dom_id menu_item %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Restaurant:</strong>
    <%= menu_item.restaurant_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= menu_item.category_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= menu_item.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= menu_item.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= menu_item.price %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Image:</strong>
    <%= link_to menu_item.image.filename, menu_item.image if menu_item.image.attached? %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this menu item", menu_item, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this menu item', edit_menu_item_path(menu_item), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/menu_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing menu item</h1>

  <%= render "form", menu_item: @menu_item %>

  <%= link_to "Show this menu item", @menu_item, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to menu items", menu_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/menu_items/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Menu items</h1>
    <%= link_to 'New menu item', new_menu_item_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="menu_items" class="min-w-full">
    <%= render @menu_items %>
  </div>
</div>

app/views/menu_items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New menu item</h1>

  <%= render "form", menu_item: @menu_item %>

  <%= link_to 'Back to menu items', menu_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/menu_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @menu_item %>

    <%= link_to 'Edit this menu_item', edit_menu_item_path(@menu_item), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this menu_item', menu_item_path(@menu_item), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to menu_items', menu_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>