config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  get 'pages/about'
  get 'pages/privacy'
  get 'pages/terms'
  get 'pages/successfulorder', to:"pages#successfulorder"
  get 'pages/index', to:"pages#index"
  get 'pages/submitorder', to:"pages#submitorder"
  get 'pages/email', to:"pages#email"
  #get "../notifications/index" => "NotificationController#index"
  

  devise_for :users,
    controllers: {
      # omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }

  resources :restaurants do
    resources :comments, module: :restaurants
    resources :menu_items
    resources :addresses, module: :restaurants
  end

  resources :comments do
    resources :comments, module: :comments
  end

  resources :categories

  resources :addresses

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flash.html.erb
<div id="flash" class="max-w-7x">
  
  <% if notice %>
    <div data-controller="alert" class="max-w-5x rounded-md bg-blue-50 p-4">
      <div class="flex">
        
        <div class="flex-shrink-0">
          <svg class="h-5 w-5 text-blue-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
          </svg>
        </div>

        <div class="ml-3">
          <p class="text-sm font-medium text-blue-800"><%= sanitize notice %></p>
        </div>

        <div class="ml-auto pl-3">
          <div class="-mx-1.5 -my-1.5">
            <%= button_tag type: 'button', data: { action: "alert#close" }, class: "inline-flex rounded-md bg-blue-50 p-1.5 text-blue-500 hover:bg-blue-100 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-blue-50" do %>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
              </svg>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  <% end %>

  <% if alert %>
    <div data-controller="alert" class="rounded-md bg-red-50 p-4">
      <div class="flex">

        <div class="flex-shrink-0">
          <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
          </svg>
        </div>

        <div class="ml-3">
          <p class="text-sm font-medium text-red-800"><%= sanitize alert %></p>
        </div>

        <div class="ml-auto pl-3">
          <div class="-mx-1.5 -my-1.5">
            <%= button_tag type: 'button', data: { action: "alert#close" }, class: "inline-flex rounded-md bg-red-50 p-1.5 text-red-500 hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-red-600 focus:ring-offset-2 focus:ring-offset-red-50" do %>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
              </svg>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  <% end %>

</div>

app/views/shared/_footer.html.erb
<footer class="bg-white">
  <div class="mx-auto max-w-7xl overflow-hidden py-20 px-6 sm:py-24 lg:px-8">
    <nav class="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12" aria-label="Footer">
      <div class="pb-6">
        <%= link_to "About", pages_about_path, class: "text-sm leading-6 text-gray-600 hover:text-gray-900" %>
      </div>

      <div class="pb-6">
        <%= link_to "Terms of Service", pages_terms_path, class: "text-sm leading-6 text-gray-600 hover:text-gray-900" %>
      </div>

      <div class="pb-6">
        <%= link_to "Privacy Policy", pages_privacy_path, class: "text-sm leading-6 text-gray-600 hover:text-gray-900" %>
      </div>z
    </nav>
    <p class="mt-10 text-center text-sm leading-5 text-gray-500">&copy; <%= Date.current.year %> ChefOnline, Inc. All rights reserved.</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="border-b border-gray-200 bg-white">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 justify-between">
      
      <%= render partial: "shared/navbar/left" %>

      <%= render partial: "shared/navbar/search" %>

      <%= render partial: "shared/navbar/right" %>      

  </div>
</nav>