config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  get 'pages/about'
  get 'pages/privacy'
  get 'pages/terms'
  get 'pages/successfulorder', to:"pages#successfulorder"
  get 'pages/index', to:"pages#index"
  get 'pages/submitorder', to:"pages#submitorder"
  get 'pages/email', to:"pages#email"
  #get "../notifications/index" => "NotificationController#index"
  

  devise_for :users,
    controllers: {
      # omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }

  resources :restaurants do
    resources :comments, module: :restaurants
    resources :menu_items
    resources :addresses, module: :restaurants
  end

  resources :comments do
    resources :comments, module: :comments
  end

  resources :categories

  resources :addresses

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id                      :bigint           not null, primary key
#  cached_votes_down       :integer          default(0)
#  cached_votes_score      :integer          default(0)
#  cached_votes_total      :integer          default(0)
#  cached_votes_up         :integer          default(0)
#  cached_weighted_average :float            default(0.0)
#  cached_weighted_score   :integer          default(0)
#  cached_weighted_total   :integer          default(0)
#  claimed                 :boolean          default(FALSE), not null
#  cuisine                 :string(200)      not null
#  description             :text             not null
#  email                   :string(100)      not null
#  favoritable_score       :text
#  favoritable_total       :text
#  hours                   :jsonb
#  name                    :string(200)      not null
#  phone                   :string(20)       not null
#  price_range             :integer          not null
#  slug                    :string           not null
#  website                 :string(200)      not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  category_id             :bigint           not null
#  user_id                 :bigint           not null
#
# Indexes
#
#  index_restaurants_on_category_id  (category_id)
#  index_restaurants_on_cuisine      (cuisine)
#  index_restaurants_on_name         (name)
#  index_restaurants_on_price_range  (price_range)
#  index_restaurants_on_slug         (slug) UNIQUE
#  index_restaurants_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#
class Restaurant < ApplicationRecord
  # include MeiliSearch::Rails

  extend FriendlyId
  # extend Pagy::Meilisearch
  extend Pagy::Searchkick

  belongs_to :user
  belongs_to :category

  has_many :menu_items, dependent: :destroy

  # has_many :addresses, through: :addresses, as: :addressable, dependent: :destroy, inverse_of: :restaurant, source: :addresses
  has_many :addresses, as: :addressable
  has_many :addressable, through: :addresses
  has_many :reviews, as: :reviewable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true

  has_one_attached :logo
  has_one_attached :banner
  has_many_attached :images

  # Broadcast changes in realtime with Hotwire
  # after_create_commit  -> { broadcast_prepend_later_to :restaurants, partial: "restaurants/index", locals: { brand: self } }
  # after_update_commit  -> { broadcast_replace_later_to self }
  # after_destroy_commit -> { broadcast_remove_to :restaurants, target: dom_id(self, :index) }

  friendly_id :name, use: :slugged

  acts_as_favoritor
  acts_as_favoritable

  acts_as_votable

  validates :name, presence: true, length: { minimum: 2, maximum: 80 }
  validates :description, presence: true, length: { minimum: 10, maximum: 5000 }
  validates :cuisine, presence: true, length: { minimum: 2, maximum: 150 }
  validates :price_range, presence: true, numericality: { only_integer: true }

  validates :email, presence: true, uniqueness: true, length: { minimum: 5, maximum: 100 }
  validates :phone,         allow_blank: true, length: { minimum: 4, maximum: 20 }
  validates :website,       allow_blank: true, length: { minimum: 4, maximum: 150 }

  validates_associated :addresses

  # meilisearch do
  #   attribute :name
  #   attribute :description
  #   attribute :cuisine
    
  #   filterable_attributes [:cuisine]
  #   sortable_attributes [:price_range, :created_at, :updated_at]
  # end

  searchkick word_start: [:name, :category, :price_range], word_middle: [:name, :category], text_middle: [:name, :category]

  def search_data
    {
      name: name,
      category: category.name,
      price_range: price_range.to_s
    }
  end
end

app/controllers/restaurants/addresses_controller.rb
class Restaurants::AddressesController < ApplicationController
	include Addressable
	before_action :set_addressable

	private

		def set_commentable
			@addressable = Address.find(params[:address_id])
		end
end

app/controllers/restaurants/comments_controller.rb
class Restaurants::CommentsController < ApplicationController
	include Commentable
	
	before_action :set_commentable

	private

		def set_commentable
			@commentable = Restaurant.friendly.find(params[:restaurant_id])
		end
end

app/controllers/restaurants/reviews_controller.rb
class Restaurants::ReviewsController < ApplicationController
	include Reviewable
	
	before_action :set_reviewable

	private

		def set_reviewable
			@reviewable = Restaurant.friendly.find(params[:restaurant_id])
		end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]
  before_action :set_header, only: %i[ index ]

  # GET /restaurants or /restaurants.json
  def index
    @pagy, @records = pagy(Restaurant.all)
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
    @restaurant.addresses.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.friendly.find(params[:id])
    end

    def set_header
      @header = "Restaurants"
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:user_id, :category_id, :name, :description, :price_range, :claimed, :email, :phone, :website, :hours, :logo, :banner, :images, addresses_attributes: [:id, :line_one, :line_two, :city, :state, :country, :zipcode, :phone, :email])
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_restaurant.html.erb
<%# restaurants.each do |restaurant| %>
  <div id="<%= dom_id restaurant %>">

    <div class="group relative flex flex-col overflow-hidden rounded-lg border border-gray-200 bg-white">
      <div class="aspect-w-3 aspect-h-4 bg-gray-200 group-hover:opacity-75 sm:aspect-none sm:h-96">
        <%= image_tag(url_for(restaurant.logo.variant(resize_to_limit: [100, 100])), class: "h-full w-full object-cover object-center sm:h-full sm:w-full") %>
        <!-- <img src="https://tailwindui.com/img/ecommerce-images/category-page-02-image-card-01.jpg" alt="Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green." class="h-full w-full object-cover object-center sm:h-full sm:w-full"> -->
      </div>
      <div class="flex flex-1 flex-col space-y-2 p-4">
        <h3 class="text-sm font-medium text-gray-900">
          <%= link_to restaurant_path(restaurant) do %>
            <span aria-hidden="true" class="absolute inset-0"></span>
            <%= restaurant.name %>
          <% end %>
        </h3>
        <p class="text-sm text-gray-500"><%= truncate(restaurant.description, length: 20) %></p>
        <div class="flex flex-1 flex-col justify-end">
          <p class="text-sm italic text-gray-500"><%= price_range_output(restaurant.price_range) %></p>
          <p class="text-base font-medium text-gray-900"><%= restaurant.category.display_name %></p>
        </div>
      </div>
    </div>

  </div>
<%# end %>

app/views/restaurants/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <%= link_to "Show this restaurant", @restaurant, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to restaurants", restaurants_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/restaurants/index.html.erb
<!-- <div class="bg-white"> -->
  <!-- <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8"> -->
    <!-- <h2 class="sr-only">Restaurants</h2> -->

    <!-- <div class="grid grid-cols-1 gap-y-4 sm:grid-cols-2 sm:gap-x-6 sm:gap-y-10 lg:grid-cols-3 lg:gap-x-8"> -->

  <!-- <div class="flex justify-between items-center"> -->
    <!-- <h1 class="font-bold text-4xl">Restaurants</h1> -->
    <%#= link_to 'New restaurant', new_restaurant_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  <!-- </div> -->

      <!-- <div id="restaurants" class="min-w-full"> -->
      <%# @records.in_groups_of(3, false) do |restaurants| %>
        <%#= render partial: "restaurants/restaurant", collection: restaurants %>
      <%# end %>
      <!-- </div> -->

    <!-- </div> -->

    <%#== pagy_nav(@pagy) %>

  <!-- </div> -->
<!-- </div> -->
<div class="bg-white">
  <div>

    <main class="mx-auto max-w-2xl px-4 py-12 sm:px-6 sm:py-20 lg:max-w-7xl lg:px-8">
      <div class="border-b border-gray-200 pb-10">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900"><%= @header %></h1>
        <p class="mt-4 text-base text-gray-500">Place an order from one or more businesses listed below.</p>
      </div>

      <div class="pt-12 lg:grid lg:grid-cols-3 lg:gap-x-8 xl:grid-cols-4">
        <aside>
          <h2 class="sr-only">Filters</h2>

          <div class="lg:block">
            <form class="space-y-10 divide-y divide-gray-200">
              <div>
                <fieldset>
                  <legend class="block text-sm font-medium text-gray-900">Color</legend>
                  <div class="space-y-3 pt-6">
                    <div class="flex items-center">
                      <input id="color-0" name="color[]" value="white" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="color-0" class="ml-3 text-sm text-gray-600">White</label>
                    </div>

                    <div class="flex items-center">
                      <input id="color-1" name="color[]" value="beige" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="color-1" class="ml-3 text-sm text-gray-600">Beige</label>
                    </div>

                    <div class="flex items-center">
                      <input id="color-2" name="color[]" value="blue" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="color-2" class="ml-3 text-sm text-gray-600">Blue</label>
                    </div>

                    <div class="flex items-center">
                      <input id="color-3" name="color[]" value="brown" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="color-3" class="ml-3 text-sm text-gray-600">Brown</label>
                    </div>

                    <div class="flex items-center">
                      <input id="color-4" name="color[]" value="green" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="color-4" class="ml-3 text-sm text-gray-600">Green</label>
                    </div>

                    <div class="flex items-center">
                      <input id="color-5" name="color[]" value="purple" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="color-5" class="ml-3 text-sm text-gray-600">Purple</label>
                    </div>
                  </div>
                </fieldset>
              </div>

              <div class="pt-10">
                <fieldset>
                  <legend class="block text-sm font-medium text-gray-900">Category</legend>
                  <div class="space-y-3 pt-6">
                    <div class="flex items-center">
                      <input id="category-0" name="category[]" value="new-arrivals" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="category-0" class="ml-3 text-sm text-gray-600">All New Arrivals</label>
                    </div>

                    <div class="flex items-center">
                      <input id="category-1" name="category[]" value="tees" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="category-1" class="ml-3 text-sm text-gray-600">Tees</label>
                    </div>

                    <div class="flex items-center">
                      <input id="category-2" name="category[]" value="crewnecks" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="category-2" class="ml-3 text-sm text-gray-600">Crewnecks</label>
                    </div>

                    <div class="flex items-center">
                      <input id="category-3" name="category[]" value="sweatshirts" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="category-3" class="ml-3 text-sm text-gray-600">Sweatshirts</label>
                    </div>

                    <div class="flex items-center">
                      <input id="category-4" name="category[]" value="pants-shorts" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="category-4" class="ml-3 text-sm text-gray-600">Pants &amp; Shorts</label>
                    </div>
                  </div>
                </fieldset>
              </div>

              <div class="pt-10">
                <fieldset>
                  <legend class="block text-sm font-medium text-gray-900">Sizes</legend>
                  <div class="space-y-3 pt-6">
                    <div class="flex items-center">
                      <input id="sizes-0" name="sizes[]" value="xs" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="sizes-0" class="ml-3 text-sm text-gray-600">XS</label>
                    </div>

                    <div class="flex items-center">
                      <input id="sizes-1" name="sizes[]" value="s" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="sizes-1" class="ml-3 text-sm text-gray-600">S</label>
                    </div>

                    <div class="flex items-center">
                      <input id="sizes-2" name="sizes[]" value="m" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="sizes-2" class="ml-3 text-sm text-gray-600">M</label>
                    </div>

                    <div class="flex items-center">
                      <input id="sizes-3" name="sizes[]" value="l" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="sizes-3" class="ml-3 text-sm text-gray-600">L</label>
                    </div>

                    <div class="flex items-center">
                      <input id="sizes-4" name="sizes[]" value="xl" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="sizes-4" class="ml-3 text-sm text-gray-600">XL</label>
                    </div>

                    <div class="flex items-center">
                      <input id="sizes-5" name="sizes[]" value="2xl" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">
                      <label for="sizes-5" class="ml-3 text-sm text-gray-600">2XL</label>
                    </div>
                  </div>
                </fieldset>
              </div>
            </form>
          </div>
        </aside>

        <!-- Product grid -->
        <!-- <section aria-labelledby="product-heading" class="mt-6 lg:col-span-2 lg:mt-0 xl:col-span-3"> -->
          <!-- <h2 id="product-heading" class="sr-only">Products</h2> -->

          <div class="mt-6 lg:col-span-2 lg:mt-0 xl:col-span-3">
          <div class="grid grid-cols-1 gap-y-4 sm:grid-cols-2 sm:gap-x-6 sm:gap-y-10 lg:gap-x-8 xl:grid-cols-3">

            <% @records.each do |record| %>
              <div class="group relative overflow-hidden rounded-lg border border-gray-200 bg-white">
                <div class="overflow-hidden bg-white px-4 py-4 shadow sm:rounded-md sm:px-6">
                  <%= image_tag url_for(record.banner.variant(resize_to_limit: [400, 800])), class: "aspect-h-4 aspect-w-3 bg-gray-200 sm:aspect-none group-hover:opacity-75 sm:h-96" %>
                  <div class="space-y-2 p-4">
                    <h3 class="text-sm font-medium text-gray-900">
                      <a href="#">
                        <span aria-hidden="true" class="absolute inset-0"></span>
                        <%= link_to record.name, restaurant_path(record) %>
                      </a>
                    </h3>
                    <p class="text-sm text-gray-500"><%= truncate(record.description, length: 50) %></p>
                    <div class="flex flex-1 flex-col justify-end">
                      <p class="text-sm italic text-gray-500"><% price_range_output(record.price_range) %></p>
                      <p class="text-base font-medium text-gray-900"><%= record.category.display_name %></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>

          </div>
        <!-- </section> -->

        


      </div>
      <%== pagy_nav(@pagy) %>
    </main>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="bg-white px-4 py-6 sm:p-8 mx-auto md:w-2/3 max-w-7xl mt-12">
  <h1 class="font-bold text-4xl">New restaurant</h1>

  <%= render "form", restaurant: @restaurant %>
</div>