config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  get 'pages/about'
  get 'pages/privacy'
  get 'pages/terms'
  get 'pages/successfulorder', to:"pages#successfulorder"
  get 'pages/index', to:"pages#index"
  get 'pages/submitorder', to:"pages#submitorder"
  get 'pages/email', to:"pages#email"
  #get "../notifications/index" => "NotificationController#index"
  

  devise_for :users,
    controllers: {
      # omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }

  resources :restaurants do
    resources :comments, module: :restaurants
    resources :menu_items
    resources :addresses, module: :restaurants
  end

  resources :comments do
    resources :comments, module: :comments
  end

  resources :categories

  resources :addresses

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id             :bigint           not null, primary key
#  ancestry       :string           not null
#  ancestry_depth :integer          default(0)
#  children_count :integer          default(0)
#  display_name   :string(100)      not null
#  name           :string(100)      not null
#  slug           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_categories_on_ancestry  (ancestry)
#  index_categories_on_slug      (slug) UNIQUE
#
class Category < ApplicationRecord
  # include MeiliSearch::Rails

	extend FriendlyId
  # extend Pagy::Meilisearch
  extend Pagy::Searchkick

  # Broadcast changes in realtime with Hotwire
  # after_create_commit  -> { broadcast_prepend_later_to :categories, partial: "categories/index", locals: { category: self } }
  # after_update_commit  -> { broadcast_replace_later_to self }
  # after_destroy_commit -> { broadcast_remove_to :categories, target: dom_id(self, :index) }

  has_many :restaurants
  has_many :menu_items

  friendly_id :display_name, use: :slugged

  searchkick word_start: [:name, :display_name], word_middle: [:name, :display_name], text_middle: [:name, :display_name]

  has_ancestry counter_cache: true, cache_depth: true

  # meilisearch do
  #   attribute :name
  #   attribute :display_name
  # end

  def search_data
    {
      name: name,
      display_name: display_name
    }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :display_name, :ancestry, :ancestry_depth, :children_count, :slug)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= category.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Display name:</strong>
    <%= category.display_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ancestry:</strong>
    <%= category.ancestry %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ancestry depth:</strong>
    <%= category.ancestry_depth %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Children count:</strong>
    <%= category.children_count %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Slug:</strong>
    <%= category.slug %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this category", category, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this category', edit_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :display_name %>
    <%= form.text_field :display_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ancestry %>
    <%= form.text_field :ancestry, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ancestry_depth %>
    <%= form.number_field :ancestry_depth, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :children_count %>
    <%= form.number_field :children_count, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :slug %>
    <%= form.text_field :slug, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <!-- <header class="py-10"> -->
    <!-- <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"> -->
      <!-- <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900">Categories</h1> -->
      <%#= link_to 'New category', new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <!-- </div> -->
  <!-- </header> -->
  <!-- <div class="flex justify-between items-center"> -->
    <!-- <h1 class="font-bold text-4xl"></h1> -->
    <%#= link_to 'New category', new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  <!-- </div> -->

  <div id="categories" class="min-w-full">
    <%= render @categories %>
  </div>
</div>

<!-- <div class="bg-white">
  <div class="py-16 sm:py-24 xl:mx-auto xl:max-w-7xl xl:px-8">
    <div class="px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8 xl:px-0">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">Shop by Category</h2>
      <a href="#" class="hidden text-sm font-semibold text-indigo-600 hover:text-indigo-500 sm:block">
        Browse all categories
        <span aria-hidden="true"> &rarr;</span>
      </a>
    </div>

    <div class="mt-4 flow-root">
      <div class="-my-2">
        <div class="relative box-content h-80 overflow-x-auto py-2 xl:overflow-visible">
          <div class="min-w-screen-xl absolute flex space-x-8 px-4 sm:px-6 lg:px-8 xl:relative xl:grid xl:grid-cols-5 xl:gap-x-8 xl:space-x-0 xl:px-0">
            <a href="#" class="relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto">
              <span aria-hidden="true" class="absolute inset-0">
                <img src="https://tailwindui.com/img/ecommerce-images/home-page-01-category-01.jpg" alt="" class="h-full w-full object-cover object-center">
              </span>
              <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50"></span>
              <span class="relative mt-auto text-center text-xl font-bold text-white">New Arrivals</span>
            </a>

            <a href="#" class="relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto">
              <span aria-hidden="true" class="absolute inset-0">
                <img src="https://tailwindui.com/img/ecommerce-images/home-page-01-category-02.jpg" alt="" class="h-full w-full object-cover object-center">
              </span>
              <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50"></span>
              <span class="relative mt-auto text-center text-xl font-bold text-white">Productivity</span>
            </a>

            <a href="#" class="relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto">
              <span aria-hidden="true" class="absolute inset-0">
                <img src="https://tailwindui.com/img/ecommerce-images/home-page-01-category-04.jpg" alt="" class="h-full w-full object-cover object-center">
              </span>
              <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50"></span>
              <span class="relative mt-auto text-center text-xl font-bold text-white">Workspace</span>
            </a>

            <a href="#" class="relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto">
              <span aria-hidden="true" class="absolute inset-0">
                <img src="https://tailwindui.com/img/ecommerce-images/home-page-01-category-05.jpg" alt="" class="h-full w-full object-cover object-center">
              </span>
              <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50"></span>
              <span class="relative mt-auto text-center text-xl font-bold text-white">Accessories</span>
            </a>

            <a href="#" class="relative flex h-80 w-56 flex-col overflow-hidden rounded-lg p-6 hover:opacity-75 xl:w-auto">
              <span aria-hidden="true" class="absolute inset-0">
                <img src="https://tailwindui.com/img/ecommerce-images/home-page-01-category-03.jpg" alt="" class="h-full w-full object-cover object-center">
              </span>
              <span aria-hidden="true" class="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-gray-800 opacity-50"></span>
              <span class="relative mt-auto text-center text-xl font-bold text-white">Sale</span>
            </a>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-6 px-4 sm:hidden">
      <a href="#" class="block text-sm font-semibold text-indigo-600 hover:text-indigo-500">
        Browse all categories
        <span aria-hidden="true"> &rarr;</span>
      </a>
    </div>
  </div>
</div> -->

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @category %>

    <%= link_to 'Edit this category', edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this category', category_path(@category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>